name: macOS RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup ngrok
        run: |
          brew install --cask ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install TigerVNC server
        run: |
          brew install tiger-vnc
          mkdir -p ~/.vnc
          VNC_PATH=$(brew --prefix tiger-vnc)/bin
          echo "123456" | $VNC_PATH/vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          $VNC_PATH/vncserver :1 -geometry 1280x720 -depth 24

      - name: Start ngrok tunnel (TCP 5901)
        run: |
          nohup ngrok tcp 5901 --log=stdout > ngrok.log &
          sleep 10
          echo "=== NGROK TCP ADDRESS ==="
          curl --silent http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[0-9a-zA-Z.:]*' || true
          echo "========================="

      - name: Keep session alive for 6 hours
        run: |
          echo "VNC running for 6 hours..."
          for i in $(seq 1 2160); do
            echo "Minute $i/360 — still alive..."
            sleep 100
          done

      - name: Cleanup
        if: always()
        run: |
          echo "Stopping VNC server..."
          VNC_PATH=$(brew --prefix tiger-vnc)/bin
          $VNC_PATH/vncserver -kill :1 || true
          echo "Done."
