name: macOS RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install ngrok
        run: |
          brew install --cask ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start VNC server
        run: |
          brew install tightvnc
          vncpasswd -f <<<"123456" > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          /usr/local/bin/vncserver :1 -geometry 1280x720 -depth 24

      - name: Start ngrok tunnel
        run: |
          nohup ngrok tcp 5901 > ngrok.log &
          sleep 10
          grep "tcp://" ngrok.log || cat ngrok.log

      - name: Keep alive
        run: |
          echo "RDP running for 6 hours..."
          sleep 21600
